### PR TITLE
Added component test for plain implementation

### PR DESCRIPTION
**Pull request by BernardTolosajr**
@xudafeng 

Im planing to add component test in all todos implementation, for now this is the test for the plain.

### CODE REVIEW

**Comment by xudafeng** [comment]
@BernardTolosajr travis-ci should be passed

**Comment by BernardTolosajr** [comment]
@xudafeng travis-ci is is failing but its all passed in my local, i will check it

**Comment by xudafeng** [comment]
@BernardTolosajr 

addtodo.vue -> addTodo.vue, due to the linux has case-insensitive? but the OSX is not

**Comment by xudafeng** [comment]
actually, we do function testing like the e2e test with Macaca to confirm our webapp's func case passed. But in single component, function unit testing with jest or vue's testing tool should be used.

**Comment by BernardTolosajr** [comment]
@xudafeng i will check the https://github.com/macacajs/torchjs, what do you think of using this https://vue-test-utils.vuejs.org/en ?

**Pull request merged**
